- name: "Template a file in /etc/profile.d"
  when:
    - item[1].enabled is defined
    - item[1].enabled
  template:
    dest: "{{ item[1].dest }}"
    src: basic.sh.j2
    mode: "{{ item[1].mode | default(0644) }}"
    owner: "{{ item[1].owner | default('root') }}"
    group: "{{ item[1].group | default('root') }}"
  loop: "{{ aspects_global_env_blocks | default({}) | dictsort(true,'key') }}"
  tags:
  - aspects_global_env

- name: "Add lines to /etc/profile"
  when:
    - item.value.enabled is defined
    - item.value.enabled
  lineinfile:
    regexp: "^.*export {{ item.key }}=.*"
    state: "{{ item.1.state }}"
    line: "{{ item.1.line }}"
    path: "/etc/profile"
  loop: "{{ aspects_global_env_lines | default({}) | dictsort(true,'key') }}"
  tags:
  - aspects_global_env
